# Generated by Django 5.1.1 on 2024-09-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="xp_skills",
            field=models.ManyToManyField(to="content.skill"),
        ),
    ]
